[package]
name = "standard_os"
version = "0.1.0"
edition = "2018"
authors = ["Igor Tiburcio Cavalcanti <igor.tiburcio.cs@gmail.com>"]

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
